name: CI

on:
  # Build every pull request, to check for regressions.
  pull_request:
    types: [opened, synchronize]

  # Build when a PR is merged, to update the README's CI badge.
  push:
    branches: [main]

  # Build once a month, to detect missing upper bounds.
  schedule:
    - cron: '0 0 1 * *'

jobs:
  stack:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Check that the build passes with the recommended snapshot.
          - name: stable
            stack_yaml: "stack.yaml"
            os: ubuntu-latest

          # Check that the lower bounds are still correct by building with the
          # lowest-supported version of all our dependencies.
          - name: oldest
            stack_yaml: "oldest-supported-lts.yaml"
            os: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      name: Cache Stack Artifacts
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles(matrix.stack_yaml) }}

    - uses: haskell/actions/setup@v1
      id: setup-haskell-stack
      name: Setup Stack
      with:
        enable-stack: true
        stack-setup-ghc: true
        stack-no-global: true

    - name: Build
      run: |
        stack --stack-yaml=${{ matrix.stack_yaml }} install --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        stack --stack-yaml=${{ matrix.stack_yaml }} test

  # Check that the build passes with the latest version of our dependencies.
  cabal:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: oldest
            ghc: latest
            os: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      name: Setup Cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    # This freeze file is regenerated on every build, so we will always test
    # with the most recent version of our dependencies allowed by our upper
    # bounds.
    - name: Freeze
      run: |
        cabal v2-configure --enable-tests --enable-benchmarks --test-show-details=direct
        cabal freeze

    # Only reuse the cached copy of our dependencies if our freeze file matches
    # the cache's copy.
    - uses: actions/cache@v2
      name: Cache Cabal Artifacts
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-cabal-v2-${{ hashFiles('cabal.project.freeze') }}

    - name: Build
      run: |
        cabal v2-build --enable-tests

    - name: Test
      run: |
        cabal v2-test
